### PR TITLE
Revise PR template

### PR DESCRIPTION
**Pull request by shlyaeva**
A revision of PR template for discussion.

### CODE REVIEW

**Comment by shlyaeva** [comment]
@climbfuji looks like very few people have access to this repo, and it would be useful to have core team review the PR template. Is it possible to add core team with read access?

**Comment by ytremolet** [comment]
> @climbfuji looks like very few people have access to this repo, and it would be useful to have core team review the PR template. Is it possible to add core team with read access?

Done.

**Review by ytremolet — APPROVED** [review]
I think it's better. Thanks.

**Comment by shlyaeva** [comment]
I think I'll add some changes suggested by @fmahebert in slack

```## Description

<!--
Provide a description ...
-->

### Issues addressed # <-- potential to remove this header

<!--
Link related issues ...
-->

### Submission/review checklist

- [ ] If PR has dependencies, add list of dependencies (from template below)
- [ ] If requires adaptation in other repos, add list of repos to adapt (from template below)
- [ ] Documentation is updated

<!--
Template for dependencies:
- waiting on ...
Template for repos to adapt:
- need to adapt ...
-->```

but it'll be next week.

**Review by fmahebert — APPROVED** [review]
I was wondering where this template lived :D

**Review by srherbener — APPROVED** [review]
Thanks for updating this!

**Review by climbfuji — APPROVED** [review]

**Comment by climbfuji** [comment]
> > @climbfuji looks like very few people have access to this repo, and it would be useful to have core team review the PR template. Is it possible to add core team with read access?
> 
> Done.

Thanks, @ytremolet . Turns out that my icloud email that receives the github notifications decided since Friday that it's all junk email ...

**Pull request closed without merging**
